import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const crimsonTextRegular = localFont({
  src: "../public/fonts/CrimsonText-Regular.ttf",
  variable: "--font-crimson-text-regular",
});

const crimsonTextBold = localFont({
  src: "../public/fonts/CrimsonText-Bold.ttf",
  variable: "--font-crimson-text-bold",
});

const montserratRegular = localFont({
  src: "../public/fonts/Montserrat-Regular.ttf",
  variable: "--font-montserrat-regular",
});

const montserratBold = localFont({
  src: "../public/fonts/Montserrat-Bold.ttf",
  variable: "--font-montserrat-bold",
});

export const metadata: Metadata = {
  title: "Ace Land - Dự án nhà ở xã hội hàng đầu Việt nam",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={`
      ${crimsonTextRegular.variable}
      ${crimsonTextBold.variable}
      ${montserratRegular.variable}
      ${montserratBold.variable}
      h-full antialiased`}
    >
      <body
        className="min-h-full flex flex-col font-sans"
        cz-shortcut-listen="true"
      >
        <Header />
        <main className="w-full flex-1">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
