import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const crimsonTextRegular = localFont({
  src: "../public/fonts/CrimsonText-Regular.ttf",
  variable: "--font-crimson-text-regular",
});

const crimsonTextBold = localFont({
  src: "../public/fonts/CrimsonText-Bold.ttf",
  variable: "--font-crimson-text-nold",
});

export const metadata: Metadata = {
  title: "Aceland",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={`${crimsonTextRegular.variable} ${crimsonTextBold.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col font-sans">
        <Header />
        <main className="w-full flex-1">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
